In [34]:
#sijisha paul_25070123138
#introduction to pandas

In [35]:
import pandas as pd
s = pd.Series([10,20,30,40])
s

0    10
1    20
2    30
3    40
dtype: int64

In [36]:
# create DataFrame
data = {
    "Name":["A","B","C"],
    "Marks": [85,90,78]
}
df= pd.DataFrame(data)
print(df)

  Name  Marks
0    A     85
1    B     90
2    C     78

In [37]:
#find the structure of the dataFrame
df.shape

(3, 2)

In [38]:
df.ndim

2

In [39]:
df.size

6

In [40]:
#display column names
df.columns

Index(['Name', 'Marks'], dtype='object')

In [41]:
#check data types of each column
df.dtypes

Name     object
Marks     int64
dtype: object

In [42]:
#access individual column
df["Name"]

0    A
1    B
2    C
Name: Name, dtype: object

In [43]:
#access anme of first row
df.loc[0,"Name"]

'A'

In [44]:
df.iloc[1]

Name      B
Marks    90
Name: 1, dtype: object

In [45]:
#add a new column
df["Grade"]=["First Class","Distinction","Second Class"]
print(df)

  Name  Marks         Grade
0    A     85   First Class
1    B     90   Distinction
2    C     78  Second Class

In [46]:
#update data in DataFrame
#change marks of students A to 88
df.loc[0,"Marsk"]=88
df.iloc[1,1]=91

In [47]:
#delete a coloumn
#df.drop("Grade",axis=1,inplace=True)
df.drop("Grade",axis=1)
print(df)
print(df)

  Name  Marks         Grade  Marsk
0    A     85   First Class   88.0
1    B     91   Distinction    NaN
2    C     78  Second Class    NaN
  Name  Marks         Grade  Marsk
0    A     85   First Class   88.0
1    B     91   Distinction    NaN
2    C     78  Second Class    NaN

In [48]:
#perform basic statistical analysis
mean1=df["Marks"].mean()
mean1

np.float64(84.66666666666667)

In [49]:
min1=df["Marks"].min()
min1

78

In [50]:
max1=df["Marks"].max()
max1

91

In [51]:
#apply condition (filtering)
#display students scoring more than 80.
df[df["Marks"]>80]

  Name  Marks        Grade  Marsk
0    A     85  First Class   88.0
1    B     91  Distinction    NaN